### ISSUE TITLE
Numberfield with controls: prevent text selection on double click

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-text-field#412] opened 2019-09-19 06:19 UTC
### Description
When using a number field with controls (+/- buttons), it can happen, that on fast usage of the buttons (e.g. hitting the plus button a few times rapidly) adjacent elemens get selected (as if I would simply double clicking them) for a short a amount of time. This leads to some ugly flickering when doing it a few times.  

Not an important issue, more a polishing thing.

### Expected outcome
Please prevent the text selection flickering on double clicking of the number field controls.

I could suppress this behavior by adding these css settings to the iron icons representing the + and -.

```
    -webkit-user-select: none; /* webkit (safari, chrome) browsers */
    -moz-user-select: none; /* mozilla browsers */
    -khtml-user-select: none; /* webkit (konqueror) browsers */
    -ms-user-select: none; /* IE10+ */
```

They should cover most of the browsers.

### Steps to reproduce
1. Open the bakery app demo.
2. Edit an existing order or create a new one.
3. Add a product.
4. Fast double click the + of the product amount field. The total amount of the product and the content of the details text field get selected for a short time.

### Environment
Seen in Chrome on a Win 10.

**Comment by web-padawan** [comment] 2020-02-14 07:25
We do have the suggested fix in place:

https://github.com/vaadin/vaadin-text-field/blob/1bc33a2d065206177372763db2bd9ed1c5126ea0/src/vaadin-number-field.html#L26-L32

I tried the steps on Windows 10 Chrome (in a virtual machine) and was unable to reproduce.

Closing, let's reopen if we confirm that the issue persists and requires a different fix.

**Closed by web-padawan** 2020-02-14 07:25 UTC
