### ISSUE TITLE
Fire "change" event on blur

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-text-field#195] opened 2018-01-18 07:09 UTC
Events in text field are different to other components like combo box, in combo-box `value-changed` and `change` are fired when the user blurs, and `input` event in any keystroke. Otherwise text-field sends `value-changed` on any key press, it does `input` one correctly, but it lacks the `change` event. All components should behave the same.

Related with https://github.com/vaadin/flow/issues/3229

**Comment by heruan** [comment] 2018-01-18 10:40
Do you mean firing the event on blur *only if* the value has actually changed, right? I'm asking this because I think it would be natural to have *all* the `input` element's events "mirrored" to the web component: more than once I was in trouble expecting to be able to listen to *focus*, *blur*, *keyup*, *keydown*, *compositionstart*, *compositionend* etc.

**Comment by manolo** [comment] 2018-01-18 11:17
> Do you mean firing the event on blur only if the value has actually changed, right?

**Comment by tomivirkki** [comment] 2018-01-23 13:54
This should behave the same as in `paper-input`: "value-changed" _should_ occur every time the text changes, "change" event should be fired once the input is blurred

**Comment by heruan** [comment] 2018-01-23 13:58
@tomivirkki Great! Seems like at the moment only the `change` event isn't "mirrored" form the wrapped `input` element, whereas all the other native events are (`input`, `keypress`, etc.). I'm not quite sure *where* this choice is implemented, since I see no `dispatchEvent` in the code for any of them 😄

**Comment by tomivirkki** [comment] 2018-01-23 14:09
@heruan Looks like the native "change" event isn't `composed` (so it doesn't cross out of the shadow root automatically) while the other events like "input" are. Should be an easy fix with the "change" event.

**Comment by manolo** [comment] 2018-01-23 14:44
> This should behave the same as in paper-input

shouldn't be aligned with date-picker and combo-box? either way or another.

**Comment by web-padawan** [comment] 2018-01-23 14:46
BTW combo-box currently dispatches `change` event when value is committed, but this event now has the `composed: true` flag. Do we want to remove it there?

**Comment by tomivirkki** [comment] 2018-01-24 08:06
> shouldn't be aligned with date-picker and combo-box? either way

It will be aligned. Neither date-picker or combo-box change their value during typing to the internal text-field, only after selecting an option. But typing to a text-field does change its value.

**Comment by tomivirkki** [comment] 2018-01-24 09:24
@web-padawan added a ticket https://github.com/vaadin/vaadin-combo-box/issues/602

**Closed** 2018-01-24 11:33 UTC
Labels: in review

**Comment by jouni** [comment] 2018-01-24 11:54
Does the change event also get fired when the user presses enter?

**Comment by web-padawan** [comment] 2018-01-24 12:06
@jouni per this [spec](https://html.spec.whatwg.org/multipage/input.html#common-input-element-events), it looks like this is expected behaviour:

> The change event fires when the value is committed, if that makes sense for the control, or else when the control loses focus

I tried with the demo and yes, the event gets fired.

**Comment by jouni** [comment] 2018-01-25 07:52
Yeah, that’s why I asked, because I believe it should be fired :)

So, all in order then! 👍
