### ISSUE TITLE
NumberField setValue renders integer values with decimal point

### ISSUE THREAD

**Issue by danieltalebi** [vaadin/vaadin-text-field#437] opened 2019-11-08 05:22 UTC
### Description
The NumberField value is rendered with a decimal point (for instance 1.0) when using .setValue(1D) even when setting the incremental step to 1. However when the value is changed using the controls, it doesn't render with the decimal point.

### Expected outcome
The value render without decimal point

### Actual outcome
The value is render with decimal point

### Live Demo
https://vaadin.com/components/vaadin-number-field/java-examples/number-field see the _Number field with value limits_ example

### Steps to reproduce
1. Create a NumberField
2. Set the value to 1 from the Java code

### Version affected
Tested with vaadin-text-field-flow-2.0.3

**Comment by web-padawan** [comment] 2019-11-08 07:17
Duplicate of vaadin/vaadin-text-field-flow#172 which was fixed by vaadin/vaadin-text-field-flow#232

The fix was released in [vaadin-text-field-flow-2.0.6](https://github.com/vaadin/vaadin-text-field-flow/releases/tag/2.0.6), please update Vaadin version to 14.0.10 or later.

**Closed by web-padawan** 2019-11-08 07:17 UTC
