### ISSUE TITLE
Click handling within TextField

### ISSUE THREAD

**Issue by syampillai** [vaadin/vaadin-text-field#225] opened 2018-05-17 13:15 UTC
Currently, clicking anywhere inside the TextField (including its prefix/suffix components) brings the focus to it. I have a prefix component on ComboBox that, when clicked, requires to pop up another user-interface for a separate user interaction. However, ComboBox gets opened when this happens and I need to close it programmatically (Also, closing the ComboBox programmatically causes a flicker on the screen.)

**Comment by web-padawan** [comment] 2018-12-18 11:50
Closing as duplicate of #125. In the meanwhile, workaround from the above comment can be used.

**Closed by web-padawan** 2018-12-18 11:50 UTC
