### ISSUE TITLE
vaadin-text-area style in readonly mode

### ISSUE THREAD

**Issue by gatanaso** [vaadin/vaadin-text-field#240] opened 2018-07-16 13:38 UTC
The `vaadin-text-area` styles are not being applied correctly when it’s in readonly mode.
There is no dashed border, or a transparent background as it is the case for the `vaadin-text-field`

1. Expected behavior:
The `vaadin-text-area` has a dashed border and transparent background when in readonly mode, such as:

<img width="213" alt="screen shot 2018-07-16 at 16 35 45" src="https://user-images.githubusercontent.com/15094658/42761460-4f98b97a-8916-11e8-92b4-f83c82095ad8.png">

2. Actual behavior:
The `vaadin-text-area` has no borders and the background is not transparent:

<img width="1211" alt="vaadin-text-area-readonly" src="https://user-images.githubusercontent.com/15094658/42761292-c2d3124c-8915-11e8-8bad-66e6018f7bcd.png">

**Comment by web-padawan** [comment] 2018-07-24 08:37
Caused by this line: https://github.com/vaadin/vaadin-text-field/blob/master/theme/lumo/vaadin-text-area-styles.html#L18

Should be fixed if we change to this one:
```css
:host(:not([readonly])) [part="input-field"]::after {
```

**Closed** 2018-07-26 14:38 UTC
Labels: in review
