### ISSUE TITLE
A TextField with setAutoselect(true) doesn't work on Android mobile (Chrome browser)

### ISSUE THREAD

**Issue by syampillai** [vaadin/vaadin-text-field#565] opened 2021-01-22 10:57 UTC
### Description
A TextField with setAutoselect(true) doesn't work on Android mobile (Chrome browser). The keyboard won't show up. Instead, a "curtain" covering the components on the screen comes up.

#### Step 1:
Create a simple view for any application and put a TextField there:  
TextField test = new TextField("Test");
test.setValue("Hello");
test.setAutoselect(true);
view.add(test);
#### Step 2:
Try to access the view from an Android mobile. Try to focus on the text field created.

### Expected Results
The text field should be editable and the keyboard of the mobile should show up.

### Actual Results
The text field is not editable and the keyboard won't show up.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] iOS Safari
- [x] Android Chrome

### Version
Tried with versions shipped with latest versions of Vaadin - 18.0.5, 18.0.4 etc.

**Comment by rolfsmeds** [comment] 2021-02-02 12:02
I haven't been able to reproduce this on Chrome for Android 86.0.4240.198. Textfield gets focus, keyboard appears and text is editable as expected.

Can you report your Chrome version and try it out on the autoselect example here https://vaadin.com/components/vaadin-text-field/java-examples/text-field

**Comment by rolfsmeds** [comment] 2021-03-01 10:50
Closing as we were not able to reproduce this.

**Closed by rolfsmeds** 2021-03-01 10:50 UTC
Labels: BFP, waiting for author
