### ISSUE TITLE
Visual focus is not restored when changing focus between OS windows

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field#138] opened 2017-09-13 14:02 UTC
Steps to reproduce:
- Focus a vaadin-text-field
- Open another browser window: focus is moved to this window
- Refocus the previous browser window
- Text field is focused, but the visual `[focused]` state is not restored

![text-field-focus](https://user-images.githubusercontent.com/66382/30381486-3c6c8f0a-98a5-11e7-92a2-2e9f42234420.gif)

For some reason, I’m not able to reproduce it at https://cdn.vaadin.com/vaadin-text-field/1.1.0-alpha4/demo/

**Comment by web-padawan** [comment] 2020-03-27 17:53
Could not reproduce with the latest version in Chrome, Safari & Firefox. Closing.

**Closed by web-padawan** 2020-03-27 17:53 UTC
