### ISSUE TITLE
The placeholder value isn't displayed when combobox is set to readonly

### ISSUE THREAD

**Issue by jm2rodriguez** [vaadin/vaadin-text-field#449] opened 2020-01-16 09:13 UTC
Vaadin: 14.1.4
Theme: Lumo

The value of the placeholder must be displayed when a Combobox is set to read-only, as is the case for HTML input fields.

**Comment by web-padawan** [comment] 2020-01-21 12:20
Thanks for the issue. Moved it to a correct repository where it should be fixed.

**Comment by web-padawan** [comment] 2020-01-21 12:21
@jouni could you please clarify whether we should mark this as a bug, or close as won't fix?

I'm not really sure but it seems like this placeholder appearance is working as intended.

**Comment by jouni** [comment] 2020-01-23 07:39
It is working as intended. We want to avoid the user thinking the field has a value.

The placeholder should primarily be used for helping the user input a value in the correct format, and if the field is read-only, there is no need for that. The placeholder should not be used as a replacement for a label or help text / description.

**Closed** 2020-01-23 07:39 UTC
