### ISSUE TITLE
Password revel button doesn't work in IE11.

### ISSUE THREAD

**Issue by aarondrabeck** [vaadin/vaadin-text-field#282] opened 2018-11-27 21:14 UTC
Expected password to be shown when icon is clicked. 

Actual behavior, password still officiated in ie11.  

All other tested browsers work.

**Comment by web-padawan** [comment] 2018-11-30 10:58
It looks like a regression was introduced right after 2.0.0 stable release in 987dab2 and landed as 2.0.1

**Closed** 2018-11-30 12:12 UTC
Labels: critical, in review
