### ISSUE TITLE
NumberField value expressed in scientific notation

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/vaadin-text-field#425] opened 2019-10-16 23:29 UTC
### Description
vaadin-number-field display double value in scientific notation, e.g. 1.2E7

### Expected outcome
vaadin-number-filed should display double value in the correct format, 12000000.00

### Actual outcome
vaadin-number-field is showing double value in scientific notation, e.g. 1.2E7

### Live Demo
![image](https://user-images.githubusercontent.com/9533785/66966379-a51a9000-f042-11e9-9fe1-0a9cf21bdbad.png)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by Haprog** [comment] 2019-10-17 05:39
Could you provide some more info please.

1. What version of vaadin-number-field are you using?
2. How are you setting the value to number field? (e.g. Polymer template binding, impreatively with JS, using Java API, please show that part of the code which sets the value)
3. Can you reproduce this in the live demos (e.g. here https://cdn.vaadin.com/vaadin-text-field/2.4.12/demo/#number-field-demos) by setting the value any way e.g. via direct user input or via JS console?

I tried setting the number field value like so (via JS):
```js
numberField.value = 12000000.00;
numberField.value = 12000000;
numberField.value = "12000000.00";
numberField.value = "12000000";
```
but I couldn't reproduce the issue.

**Comment by allenvpn312** [comment] 2019-10-17 06:02
I think I posted in the wrong project, should be vaadin-text-field-flow.

The issue occured when value > 9999999.  I'll post the bug there.

**Comment by Haprog** [comment] 2019-10-17 06:05
We can transfer this issue to the correct repository if you didn't create a new one yet.

**Comment by allenvpn312** [comment] 2019-10-17 06:17
I just submitted it, thank you.

**Comment by Haprog** [comment] 2019-10-22 06:31
Since you opened the new issue I'm closing this as a duplicate of https://github.com/vaadin/vaadin-text-field-flow/issues/243 (but that seems to be fixed already).

**Closed by Haprog** 2019-10-22 06:31 UTC
