### ISSUE TITLE
Dialog interferes with scrollbar behavior in inner components

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-text-field#409] opened 2018-11-14 22:14 UTC
Vaadin version: 11.0.0
If you create a TextArea (didn't try with other components) with enough inner text that makes the scrollbar to appear, then the very same TextArea, inside a dialog, will not show the scrollbars, until you modify the inner text:
![scrollingproblem](https://user-images.githubusercontent.com/28312758/48516034-240ab580-e841-11e8-8168-f2211e39285d.gif)
This can be reproduced with this code:
```
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
    	TextArea t = new TextArea("Enter text");
    	t.setHeight("150px");
    	t.setValue("Just a line\r\nJust a line\r\nJust a line\r\nJust a line\r\nJust a line\r\nJust a line\r\nJust a line\r\n");
    	Button b = new Button("Open Dialog");
    	b.addClickListener(e->{
    		Dialog d = new Dialog();
    		TextArea t2 = new TextArea("Enter text");
        	t2.setValue("Just a line\r\nJust a line\r\nJust a line\r\nJust a line\r\nJust a line\r\nJust a line\r\nJust a line\r\n");
        	t2.setHeight("150px");
    		d.add(t2);
    		d.open();
    	});
    
    	add(t,b);
    }
}
```

**Comment by web-padawan** [comment] 2020-02-17 18:58
I could not reproduce this issue using given code with the latest Dialog and TextArea versions.

The code from https://github.com/vaadin/vaadin-text-field-flow/issues/132#issuecomment-470486861 also works (scrollbar is shown).

## Chrome on Windows 10

<img width="671" alt="chrome-win" src="https://user-images.githubusercontent.com/10589913/74678972-2a66aa80-51c5-11ea-87d9-868303412167.png">

## Edge 18 on Windows 10

<img width="663" alt="edge-win" src="https://user-images.githubusercontent.com/10589913/74679988-0ce71000-51c8-11ea-8384-e8b4f7b131cf.png">

## Chrome on Mac OS

<img width="808" alt="chrome-mac" src="https://user-images.githubusercontent.com/10589913/74679010-466a4c00-51c5-11ea-99fe-c62c80ef6cdd.png">

Closing as this bug appears to be fixed with Vaadin 14 and 15.
Please comment if the problem persists and we will reopen.

**Closed by web-padawan** 2020-02-17 18:58 UTC
