### ISSUE TITLE
[material] autocomplete affects label appearance on Windows

### ISSUE THREAD

**Issue by xkotj** [vaadin/vaadin-text-field#378] opened 2019-05-21 09:05 UTC
### Description
Using - material theme
When value is selected from history it show blue box covering label and input field is not responsive, can not change value. Value is not valid.

import "@vaadin/vaadin-text-field/theme/material/vaadin-email-field.js";
......
html `
<vaadin-email-field label="E-mail" name="email" required></vaadin-email-field>
`

### Expected outcome
Blue box not covering label, editable, valid value
![image](https://user-images.githubusercontent.com/42933817/58082858-1e0edc00-7bb8-11e9-9f42-2163a5e54355.png)

### Outcome
Wrong render
![image](https://user-images.githubusercontent.com/42933817/58082477-5eba2580-7bb7-11e9-9db3-5468d5a68f16.png)

### Browsers Affected

- [x ] Chrome
- [x ] Firefox

**Comment by xkotj** [comment] 2019-05-21 09:51
Found more precise specification:

Steps to reproduce:
autocomplete="on" <- default value

1. Start typing
2. History pops out
3. Hover mouse on any value
4. move mouse out of the history box
5. click
6. Value is shown in input field and it is not editable

**Comment by web-padawan** [comment] 2019-05-29 06:27
Hi, can you please inform us what operation system are you using?

**Comment by xkotj** [comment] 2019-05-29 10:40
Hi, I am using Windows 10.
Chrome 74.0.3729.169

Problem occurs even in valo theme in example here:
https://vaadin.com/components/vaadin-email-field/html-examples/email-field-demos

Blue box from autocompletion is ok (not covering label), but when you do steps I have described.
There will be uneditable text. Sometimes helps to put cursor on text start, but that is not a rule.

Regards,
JK

**Comment by pekam** [comment] 2019-06-11 08:38
Hi!

It seems to me that you have discovered a bug in Chrome. When hovering over the suggestions in the autocomplete dropdown, Chrome renders the current option in the input-field with a blue background (this is different compared to Firefox at least). When moving the mouse outside of the dropdown, Chrome should clear the input field and remove the blue background.

The bug occurs when an input with autocomplete is placed inside a shadow root. In this case, when moving mouse out of the overlay, the input is not cleared. It leaves the input element in a weird state where it's value is empty, but it still displays the suggested option in the field as un-editable.

Here's a minimal piece of HTML to test both the expected behavior and the buggy case inside shadow DOM:
```html
<body>
  <input autocomplete="on" name="username">
  <div></div>
  <script>
    const shadowRoot = document.querySelector('div').attachShadow({ mode: 'open' });
    shadowRoot.innerHTML = '<input autocomplete="on" name="username">';
  </script>
</body>
```

Another issue is that the blue highlight (which also remains visible when selecting one of the suggested values) covers the text field's label when using material theme. Personally I think that it doesn't look very nice even with Lumo theme, and the blue highlight should maybe be just disabled for `<vaadin-text-field>`. That might not be very easy though, as it's part of Chrome's implementation of `<input>`.

**Comment by web-padawan** [comment] 2019-06-11 12:03
Let's discuss the autofill style in https://github.com/vaadin/vaadin-text-field/issues/196

**Comment by pekam** [comment] 2019-06-11 13:10
Bug reported for Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=973018&can=2&q=autocomplete%20shadow%20dom

**Comment by pekam** [comment] 2019-06-11 14:24
A small improvement would be to set the label on top of the blue highlight in Material theme by using `z-index`, but when experiencing that Chrome bug, it would look even worse as the label stacks on top of the autofill value.

I'll close the issue as there's a general ticket for improving the styling with autocomplete #196, and because the other issue was a browser bug.

**Closed by pekam** 2019-06-11 14:24 UTC
Labels: needs research
