### ISSUE TITLE
Input e-mail on mobile browser

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field#260] opened 2018-09-27 15:45 UTC
When an `<input>` has `type="email"` in major mobile browser the on-screen keyboard adapts to facilitate typing e-mails. It would be great to have this also in `vaadin-text-field` (similar also other type shows specific keyboard).

**Comment by web-padawan** [comment] 2018-09-27 16:21
Thanks for the issue. This appears to be duplicate of #204 so I'm closing this for now.
One potential solution would be to implement #67 in the future version of component.

**Closed by web-padawan** 2018-09-27 16:21 UTC
