### ISSUE TITLE
numeric input with up/down arrow 

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-text-field#208] opened 2018-03-15 09:42 UTC
Currently it is possible to create a numeric input with paper-input by setting the 'type' attribute to 'number'. Can this be done in vaadin-text-field as well?

**Comment by jouni** [comment] 2018-03-15 09:53
Thanks for the question. This is a duplicate of #204 and eventually fixed by #110.

**Closed by jouni** 2018-03-15 09:53 UTC

**Comment by sudipta1411** [comment] 2018-03-15 10:15
Thanks for the swift reply
