### ISSUE TITLE
[BUG] - Incorrect rendering: Text field / flex grow does not respect outer margin

### ISSUE THREAD

**Issue by markhm** [vaadin/vaadin-text-field#549] opened 2020-11-21 11:30 UTC
**Describe the bug**
On iOS 14.2 (latest) on an iPhone X, the vaadin-text-field with style="flex-grow: 1;" does not render correctly on the Safari browser. See that on attached image the phone number value box does not stop on the right outline. (Note that the incorrect rendering of the avatar at the top - also in this image - is unrelated to this issue.)

**To Reproduce**
1. Go to 'start.vaadin.com'
2. Create a new start application with the Person Form template in TypeScript + HTML  
3. Download and run the application locally
4. Browse with an iPhone X to the correct location and observe the error.

**Expected behavior**
The text field should respect the correct outer margin. 

**Screenshots**
![IMG_7187](https://user-images.githubusercontent.com/1430451/99875747-366b1700-2bf2-11eb-999e-178e5167f82f.jpg)

**Desktop (please complete the following information):**
 - OS: iOS 14.2
 - Browser Safari, Brave
 - Version latest
 - Vaadin platform version 17.0.9

**Additional context**
None.

**Comment by rolfsmeds** [comment] 2020-12-01 16:29
Screenshot of the same problem with Chrome 86 on OSX:
![image](https://user-images.githubusercontent.com/4611559/100763882-6b4f4900-33fe-11eb-9562-34c9cfc97113.png)

This does not seem to be specific to iOS nor Safari, but is probably caused by `vaadin-text-field` refusing to shrink smaller than its default width (as determined by `width: var(--vaadin-text-field-default-width, 12em)` on the `vaadin-text-field-container` div inside its shadow dom).

(This can be tested by giving a bigger value to that variable, which makes the issue much more prominent.)

If the textfield in question has a width set, this problem does not occur, presumably because the max-width:100% of `vaadin-text-field-container` would respect that. (As an example, the other fields in the form _do_ have a specified width as `vaadin-form-layout` gives them one.)

**So the problem is that a `vaadin-text-field` with no width specified won't shrink beyond the default width specified by `var(--vaadin-text-field-default-width, 12em)`.**

As for a fix, I'm not sure what would be best:
- Set overflow:hidden on `vaadin-text-field`? (not sure if this could break something in some situations)
- Change the css of `vaadin-text-field-container` div somehow? (not sure how -- setting its `min-width:0` has no effect)

**Comment by jouni** [comment] 2020-12-01 16:42
As a side note: I see `width: 120px` set on the `<vaadin-text-field>`, in the Person Form view template, when inspecting it directly on start.vaadin.com, which makes the issue less easy to spot, as the field can shrink smaller than the default minimun width. It looks like there is a difference between the preview and what you get when downloading (I’ll report that in another repo).

As for this issue: the current behavior is by design, and mimics how the native `<input type="text">` element behaves. With the native input, you also need to explicitly set `min-width: 0` (or small enough for your use case) to make it shrink within a flex container.

The fix should be done in the view template. No fix needed in the component itself.

**Comment by rolfsmeds** [comment] 2020-12-01 20:35
Closing this in favor of
https://github.com/vaadin/vaadin-text-field/issues/560
and
https://github.com/vaadin/starter-wizard/issues/833

**Closed by rolfsmeds** 2020-12-01 20:35 UTC
Labels: Impact: Low, Severity: Minor
